# -*- coding: utf-8 -*-
"""Part B.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m2LRSVHvqJTESwlzYHpuQbCLonZbAWoA
"""

def calculate_tax(income):

    standard_deduction = 75000
    taxable_income = max(0, income - standard_deduction)

    slabs = [
        (0, 300000, 0.00),
        (300000, 700000, 0.05),
        (700000, 1000000, 0.10),
        (1000000, 1200000, 0.15),
        (1200000, 1500000, 0.20),
        (1500000, float('inf'), 0.30)
    ]

    total_tax = 0
    breakdown = []

    for lower, upper, rate in slabs:
        if taxable_income > lower:
            taxable_amount = min(taxable_income, upper) - lower
            tax = taxable_amount * rate
            total_tax += tax

            breakdown.append({
                "slab": f"{lower} - {upper if upper != float('inf') else 'Above'}",
                "income_in_slab": taxable_amount,
                "rate": rate,
                "tax": tax
            })

    return taxable_income, breakdown, total_tax


income = float(input("Enter Annual Income (₹): "))

taxable_income, breakdown, total_tax = calculate_tax(income)

print("\n----- TAX BREAKDOWN -----")
print(f"Original Income: ₹{income:,.2f}")
print(f"Standard Deduction: ₹75,000")
print(f"Taxable Income: ₹{taxable_income:,.2f}\n")

for item in breakdown:
    print(f"Slab: {item['slab']}")
    print(f"Income in Slab: ₹{item['income_in_slab']:,.2f}")
    print(f"Rate: {item['rate']*100}%")
    print(f"Tax: ₹{item['tax']:,.2f}")
    print()

print("-------------------------")
print(f"Total Tax: ₹{total_tax:,.2f}")

effective_rate = (total_tax / income) * 100 if income > 0 else 0
print(f"Effective Tax Rate: {effective_rate:.2f}%")