# -*- coding: utf-8 -*-
"""Part A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x02_R1nYb0UP7eJgN4cbloxKWD7B7eh2
"""

"""
Student Admission Decision System
A comprehensive admission screening tool with validation and decision logic
"""

from dataclasses import dataclass
from enum import Enum
from typing import Union, Tuple


class Category(Enum):
    GENERAL = "general"
    OBC = "obc"
    SC_ST = "sc_st"


class Decision(Enum):
    ADMITTED_SCHOLARSHIP = "ADMITTED (Scholarship)"
    ADMITTED_REGULAR = "ADMITTED (Regular)"
    WAITLISTED = "WAITLISTED"
    REJECTED = "REJECTED"


@dataclass
class StudentApplication:
    entrance_score: float
    gpa: float
    has_recommendation: str
    category: str
    extracurricular_score: float


class AdmissionSystem:
    # Category minimums
    CATEGORY_MINIMUMS = {
        Category.GENERAL: 75,
        Category.OBC: 65,
        Category.SC_ST: 55
    }

    # Constants
    MIN_GPA = 7.0
    SCHOLARSHIP_THRESHOLD = 95
    RECOMMENDATION_BONUS = 5
    EXTRACURRICULAR_BONUS = 3
    EXTRACURRICULAR_THRESHOLD = 8

    def __init__(self):
        self.bonuses_applied = []
        self.effective_score = 0
        self.reasoning = []

    def validate_inputs(self, app: StudentApplication) -> Tuple[bool, str]:
        """Comprehensive input validation with specific error messages."""
        errors = []

        # Validate entrance_score
        if not isinstance(app.entrance_score, (int, float)):
            errors.append("Entrance score must be a number")
        elif not (0 <= app.entrance_score <= 100):
            errors.append(f"Entrance score must be between 0 and 100 (got {app.entrance_score})")

        # Validate GPA
        if not isinstance(app.gpa, (int, float)):
            errors.append("GPA must be a number")
        elif not (0 <= app.gpa <= 10):
            errors.append(f"GPA must be between 0 and 10 (got {app.gpa})")

        # Validate recommendation
        rec_lower = str(app.has_recommendation).lower().strip()
        if rec_lower not in ['yes', 'no', 'true', 'false', '1', '0']:
            errors.append(f"Recommendation must be 'yes' or 'no' (got '{app.has_recommendation}')")

        # Validate category
        cat_lower = str(app.category).lower().strip()
        valid_categories = ['general', 'obc', 'sc_st', 'sc/st', 'sc-st']
        if cat_lower not in valid_categories:
            errors.append(f"Category must be 'general', 'obc', or 'sc_st' (got '{app.category}')")

        # Validate extracurricular_score
        if not isinstance(app.extracurricular_score, (int, float)):
            errors.append("Extracurricular score must be a number")
        elif not (0 <= app.extracurricular_score <= 10):
            errors.append(f"Extracurricular score must be between 0 and 10 (got {app.extracurricular_score})")

        if errors:
            return False, "VALIDATION ERROR: " + "; ".join(errors)
        return True, ""

    def normalize_inputs(self, app: StudentApplication) -> StudentApplication:
        """Normalize string inputs to standard formats."""
        rec = str(app.has_recommendation).lower().strip()
        has_rec = rec in ['yes', 'true', '1']

        cat = str(app.category).lower().strip().replace('/', '_').replace('-', '_')
        if cat == 'sc_st':
            cat = 'sc_st'

        return StudentApplication(
            entrance_score=float(app.entrance_score),
            gpa=float(app.gpa),
            has_recommendation="yes" if has_rec else "no",
            category=cat,
            extracurricular_score=float(app.extracurricular_score)
        )

    def calculate_bonuses(self, app: StudentApplication) -> Tuple[float, list]:
        """Calculate total bonuses and return detailed breakdown."""
        bonuses = []
        total_bonus = 0

        # Recommendation bonus
        if app.has_recommendation == "yes":
            total_bonus += self.RECOMMENDATION_BONUS
            bonuses.append(f"+{self.RECOMMENDATION_BONUS} (recommendation)")

        # Extracurricular bonus
        if app.extracurricular_score > self.EXTRACURRICULAR_THRESHOLD:
            total_bonus += self.EXTRACURRICULAR_BONUS
            bonuses.append(f"+{self.EXTRACURRICULAR_BONUS} (extracurricular)")

        return total_bonus, bonuses

    def evaluate(self, app: StudentApplication) -> dict:
        """
        Main evaluation engine implementing all business rules.
        Returns comprehensive result with reasoning.
        """
        # Reset state
        self.bonuses_applied = []
        self.reasoning = []

        # Step 1: Validation
        is_valid, error_msg = self.validate_inputs(app)
        if not is_valid:
            return {
                "decision": Decision.REJECTED.value,
                "reason": error_msg,
                "effective_score": None,
                "bonuses": [],
                "passed_validation": False
            }

        # Step 2: Normalize inputs
        app = self.normalize_inputs(app)
        category_enum = Category(app.category)

        # Step 3: Merit Rule (Auto-admit with scholarship)
        if app.entrance_score >= self.SCHOLARSHIP_THRESHOLD:
            return {
                "decision": Decision.ADMITTED_SCHOLARSHIP.value,
                "reason": f"Exceptional merit: Entrance score {app.entrance_score} ≥ {self.SCHOLARSHIP_THRESHOLD}. "
                         f"All other criteria waived.",
                "effective_score": app.entrance_score,
                "bonuses": [],
                "passed_validation": True,
                "scholarship": True
            }

        # Step 4: Calculate bonuses
        total_bonus, self.bonuses_applied = self.calculate_bonuses(app)
        self.effective_score = app.entrance_score + total_bonus

        # Step 5: Check GPA requirement (universal)
        if app.gpa < self.MIN_GPA:
            return {
                "decision": Decision.REJECTED.value,
                "reason": f"GPA requirement not met: {app.gpa} < {self.MIN_GPA} (minimum required for all categories)",
                "effective_score": self.effective_score,
                "bonuses": self.bonuses_applied,
                "passed_validation": True,
                "rejection_cause": "GPA below minimum"
            }

        # Step 6: Check category-specific entrance score minimum
        category_min = self.CATEGORY_MINIMUMS[category_enum]

        if app.entrance_score < category_min:
            # Check if bonuses could help (for transparency)
            if self.effective_score >= category_min:
                bonus_info = f" (Note: With bonuses, effective score {self.effective_score} would meet cutoff, "
                bonus_info += "but raw score is used for minimum eligibility)"
            else:
                bonus_info = ""

            return {
                "decision": Decision.REJECTED.value,
                "reason": f"Entrance score below {app.category.upper()} category minimum: "
                         f"{app.entrance_score} < {category_min}{bonus_info}",
                "effective_score": self.effective_score,
                "bonuses": self.bonuses_applied,
                "passed_validation": True,
                "rejection_cause": "Category minimum not met"
            }

        # Step 7: Final decision based on effective score vs threshold
        buffer_above_minimum = self.effective_score - category_min

        if buffer_above_minimum >= 10:
            decision = Decision.ADMITTED_REGULAR
            reason = (f"Strong candidate: Effective score {self.effective_score} significantly exceeds "
                     f"{app.category.upper()} cutoff of {category_min} (buffer: +{buffer_above_minimum}). "
                     f"GPA {app.gpa} meets requirement (≥{self.MIN_GPA}).")
        elif buffer_above_minimum >= 0:
            decision = Decision.WAITLISTED
            reason = (f"Marginal candidate: Effective score {self.effective_score} meets {app.category.upper()} "
                     f"cutoff of {category_min} but with narrow margin (+{buffer_above_minimum}). "
                     f"GPA {app.gpa} meets requirement. Subject to seat availability.")
        else:
            # This shouldn't happen given earlier checks, but for safety
            decision = Decision.REJECTED
            reason = f"Effective score {self.effective_score} below required threshold after bonuses."

        return {
            "decision": decision.value,
            "reason": reason,
            "effective_score": self.effective_score,
            "raw_score": app.entrance_score,
            "bonuses": self.bonuses_applied,
            "passed_validation": True,
            "category": app.category,
            "gpa": app.gpa
        }


def format_output(result: dict) -> str:
    """Format the evaluation result for display."""
    output = []
    output.append("=" * 60)
    output.append("ADMISSION DECISION REPORT")
    output.append("=" * 60)

    if not result.get("passed_validation"):
        output.append(f"\n❌ {result['decision']}")
        output.append(f"Details: {result['reason']}")
        output.append("=" * 60)
        return "\n".join(output)

    output.append(f"\nDecision: {result['decision']}")

    if result.get('scholarship'):
        output.append(f"\n🏆 MERIT SCHOLARSHIP AWARDED")
        output.append(f"Raw Score: {result['effective_score']}")
    else:
        output.append(f"\nRaw Entrance Score: {result.get('raw_score', 'N/A')}")
        if result.get('bonuses'):
            output.append(f"Bonus Applied: {' '.join(result['bonuses'])}")
            output.append(f"Effective Score: {result['effective_score']}")
        else:
            output.append("Bonus Applied: None")

    output.append(f"\nReasoning: {result['reason']}")
    output.append("=" * 60)
    return "\n".join(output)


# ==================== TEST CASES ====================

def run_tests():
    """Run comprehensive test cases."""
    system = AdmissionSystem()

    test_cases = [
        # (description, StudentApplication)
        (
            "Sample Input from Problem",
            StudentApplication(72, 8.5, "yes", "general", 9)
        ),
        (
            "Auto-admit Scholarship (Merit Rule)",
            StudentApplication(96, 6.0, "no", "general", 5)
        ),
        (
            "GPA Too Low",
            StudentApplication(85, 6.5, "yes", "general", 9)
        ),
        (
            "General Category - Rejected Below 75",
            StudentApplication(74, 8.0, "no", "general", 5)
        ),
        (
            "OBC Category - Admitted with Bonuses",
            StudentApplication(62, 8.0, "yes", "obc", 9)
        ),
        (
            "SC/ST Category - Barely Meets",
            StudentApplication(55, 7.5, "no", "sc_st", 5)
        ),
        (
            "Waitlisted - Marginal General",
            StudentApplication(76, 8.0, "no", "general", 5)
        ),
        (
            "Invalid - Negative Score",
            StudentApplication(-5, 8.0, "yes", "general", 5)
        ),
        (
            "Invalid - Wrong Category",
            StudentApplication(80, 8.0, "yes", "international", 5)
        ),
        (
            "Strong OBC with Full Bonuses",
            StudentApplication(70, 9.0, "yes", "obc", 9)
        ),
    ]

    print("\n" + "=" * 80)
    print("RUNNING COMPREHENSIVE TEST SUITE")
    print("=" * 80 + "\n")

    for desc, app in test_cases:
        print(f"\n{'─' * 80}")
        print(f"TEST: {desc}")
        print(f"Inputs: Score={app.entrance_score}, GPA={app.gpa}, "
              f"Rec={app.has_recommendation}, Cat={app.category}, Extra={app.extracurricular_score}")
        print(f"{'─' * 80}")

        result = system.evaluate(app)
        print(format_output(result))

    # Interactive mode
    print("\n" + "=" * 80)
    print("INTERACTIVE MODE")
    print("=" * 80)
    interactive_mode(system)


def interactive_mode(system: AdmissionSystem):
    """Allow user to input custom values."""
    print("\nEnter student details (or 'quit' to exit):")

    while True:
        try:
            score = input("\nEntrance Score (0-100): ").strip()
            if score.lower() == 'quit':
                break

            gpa = input("GPA (0-10): ").strip()
            rec = input("Recommendation (yes/no): ").strip()
            cat = input("Category (general/obc/sc_st): ").strip()
            extra = input("Extracurricular Score (0-10): ").strip()

            app = StudentApplication(
                entrance_score=float(score),
                gpa=float(gpa),
                has_recommendation=rec,
                category=cat,
                extracurricular_score=float(extra)
            )

            result = system.evaluate(app)
            print(format_output(result))

        except ValueError as e:
            print(f"Input error: Please enter valid numbers. ({e})")
        except Exception as e:
            print(f"Error: {e}")


if __name__ == "__main__":
    run_tests()