# -*- coding: utf-8 -*-
"""transaction_validator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11QghVOpNfnA3zT13-dzTCaxrA-nQkOFW
"""

amount = int(input("Enter transaction amount: "))
category = input("Enter category (food/travel/electronics/other): ").lower()
hour = int(input("Enter hour (0-23): "))
daily_spent_so_far = int(input("Enter daily spent so far: "))
vip = input("VIP customer? (yes/no): ").lower()

multiplier = 2 if vip == "yes" else 1

food_limit = 5000 * multiplier
electronics_limit = 30000 * multiplier

if amount > 50000 * multiplier:
    print("BLOCKED: exceeds single transaction limit")

elif daily_spent_so_far + amount > 100000 * multiplier:
    print("BLOCKED: exceeds daily spending limit")

elif hour < 6 or hour > 23:
    print("FLAGGED: unusual transaction time")

elif category == "food" and amount > food_limit:
    print("FLAGGED: exceeds food category limit")

elif category == "electronics" and amount > electronics_limit:
    print("FLAGGED: exceeds electronics category limit")

else:
    print("APPROVED")